In [19]:
#PART 1
#1 --> solution in pdf of images, attached

In [20]:
'''
2 and 3
'''

#defining function from assignment as well as the 1D gradient defined as partial derivative
def f(x):
    return -(x*x)

def gradient(x):
    return -(2*x)

#iterative gradient ascent function
def gradientAscent(x0, r, iterations, e):
    x=x0
    iterCount=1
    while(iterCount<=iterations):
        print("x->{0}".format(x))
        print("f(x)->{0}".format(f(x)))
        print("gradient->{0}".format(gradient(x)))
        x = x + r * gradient(x)
        print("recomputed x->{0}".format(x))
        if(abs(gradient(x))<e):
            print("maxima reached in {0} iterations!".format(iterCount))
            break
        iterCount+=1

#running gradient ascent functions with various starting paramters
gradientAscent(x0=1, r=0.1, iterations=20, e=0.05)
print("--------------------------------------------------")
gradientAscent(x0=2, r=0.2, iterations=20, e=0.005)
print("--------------------------------------------------")
gradientAscent(x0=1, r=0.1, iterations=20, e=0.0005)
print("--------------------------------------------------")


x->1
f(x)->-1
gradient->-2
recomputed x->0.8
x->0.8
f(x)->-0.6400000000000001
gradient->-1.6
recomputed x->0.64
x->0.64
f(x)->-0.4096
gradient->-1.28
recomputed x->0.512
x->0.512
f(x)->-0.262144
gradient->-1.024
recomputed x->0.4096
x->0.4096
f(x)->-0.16777216
gradient->-0.8192
recomputed x->0.32768
x->0.32768
f(x)->-0.10737418240000002
gradient->-0.65536
recomputed x->0.26214400000000004
x->0.26214400000000004
f(x)->-0.06871947673600003
gradient->-0.5242880000000001
recomputed x->0.20971520000000005
x->0.20971520000000005
f(x)->-0.04398046511104002
gradient->-0.4194304000000001
recomputed x->0.16777216000000003
x->0.16777216000000003
f(x)->-0.02814749767106561
gradient->-0.33554432000000006
recomputed x->0.13421772800000004
x->0.13421772800000004
f(x)->-0.018014398509481992
gradient->-0.26843545600000007
recomputed x->0.10737418240000003
x->0.10737418240000003
f(x)->-0.011529215046068476
gradient->-0.21474836480000006
recomputed x->0.08589934592000002
x->0.08589934592000002
f(x)->-0.0

In [21]:
#4,5,6 --> solution in pdf of images, attached

In [22]:
#7,8
#2D case
x0 = np.array([2,-3])
a = np.array([[1,2],[2,8]])


def f(a,x):
    return -1*np.matmul(np.transpose(x),np.matmul(a,x))

def gradient(a,x):
    return -2*(np.matmul(a,x))

#iterative gradient ascent function
def gradientAscent2D(x0, r, iterations, e):
    x=x0
    iterCount=1
    while(iterCount<=iterations):
        print("x->{0}".format(x))
        print("f(x)->{0}".format(f(a,x)))
        print("gradient->{0}".format(gradient(a,x)))
        x = x + r * gradient(a,x)
        print("recomputed x->{0}".format(x))
        '''
        if(abs(gradient(a,x))<e):
            print("maxima reached in {0} iterations!".format(iterCount))
            break
        '''
        iterCount+=1

#print(f(a,x0))
#print(gradient(a,x0))

gradientAscent2D(x0, 0.1, 50, 0.05)


x->[ 2 -3]
f(x)->-52
gradient->[ 8 40]
recomputed x->[ 2.8  1. ]
x->[ 2.8  1. ]
f(x)->-27.04
gradient->[ -9.6 -27.2]
recomputed x->[ 1.84 -1.72]
x->[ 1.84 -1.72]
f(x)->-14.393600000000005
gradient->[  3.2   20.16]
recomputed x->[ 2.16   0.296]
x->[ 2.16   0.296]
f(x)->-7.923968000000005
gradient->[ -5.504 -13.376]
recomputed x->[ 1.6096 -1.0416]
x->[ 1.6096 -1.0416]
f(x)->-4.564019200000003
gradient->[  0.9472  10.2272]
recomputed x->[ 1.70432 -0.01888]
x->[ 1.70432 -0.01888]
f(x)->-2.7788480512000016
gradient->[-3.33312 -6.5152 ]
recomputed x->[ 1.371008 -0.6704  ]
x->[ 1.371008 -0.6704  ]
f(x)->-1.7986571632640012
gradient->[-0.060416  5.242368]
recomputed x->[ 1.3649664 -0.1461632]
x->[ 1.3649664 -0.1461632]
f(x)->-1.2360112937369607
gradient->[-2.14528   -3.1212544]
recomputed x->[ 1.1504384  -0.45828864]
x->[ 1.1504384  -0.45828864]
f(x)->-0.8948049336598534
gradient->[-0.46772224  2.73086464]
recomputed x->[ 1.10366618 -0.18520218]
x->[ 1.10366618 -0.18520218]
f(x)->-0.6748722865

In [23]:
#9

x0 = np.array([10,20,30,40,50])
a = np.array([[11,4,7,10,13],[4,17,10,13,16],[7,10,23,16,29],[10,13,16,29,22],[13,16,19,22,25]])


def f(a,x):
    return -1*np.matmul(np.transpose(x),np.matmul(a,x))

def gradient(a,x):
    return -2*(np.matmul(a,x))

#iterative gradient ascent function
def gradientAscent2D(x0, r, iterations, e):
    x=x0
    iterCount=1
    while(iterCount<=iterations):
        print("x->{0}".format(x))
        print("f(x)->{0}".format(f(a,x)))
        print("gradient->{0}".format(gradient(a,x)))
        x = x + r * gradient(a,x)
        print("recomputed x->{0}".format(x))
        '''
        if(abs(gradient(a,x))<e):
            print("maxima reached in {0} iterations!".format(iterCount))
            break
        '''
        iterCount+=1

#print(f(a,x0))
#print(gradient(a,x0))

gradientAscent2D(x0, 0.1, 50, 0.05)

x->[10 20 30 40 50]
f(x)->-427500
gradient->[-2900 -4000 -6100 -6200 -6300]
recomputed x->[-280. -380. -580. -580. -580.]
x->[-280. -380. -580. -580. -580.]
f(x)->-98720000.0
gradient->[ 44000.  60400.  90400.  93200.  96000.]
recomputed x->[ 4120.  5660.  8460.  8740.  9020.]
x->[ 4120.  5660.  8460.  8740.  9020.]
f(x)->-22362864000.0
gradient->[ -663680.  -910480. -1362880. -1404080. -1445280.]
recomputed x->[ -62248.  -85388. -127828. -131668. -135508.]
x->[ -62248.  -85388. -127828. -131668. -135508.]
f(x)->-5077323161600.0
gradient->[  9998720.  13717360.  20532160.  21154640.  21777120.]
recomputed x->[  937624.  1286348.  1925388.  1983796.  2042204.]
x->[  937624.  1286348.  1925388.  1983796.  2042204.]
f(x)->-1152534350736000.0
gradient->[ -1.50647168e+08  -2.06673808e+08  -3.09350848e+08  -3.18727088e+08
  -3.28103328e+08]
recomputed x->[-14127092.8 -19381032.8 -29009696.8 -29888912.8 -30768128.8]
x->[-14127092.8 -19381032.8 -29009696.8 -29888912.8 -30768128.8]
f(x)->-2.616

f(x)->-2.0813917286540068e+76
gradient->[ -6.40192152e+38  -8.78283964e+38  -1.31462128e+39  -1.35446759e+39
  -1.39431389e+39]
recomputed x->[ -6.00345846e+37  -8.23618547e+37  -1.23279772e+38  -1.27016395e+38
  -1.30753017e+38]
x->[ -6.00345846e+37  -8.23618547e+37  -1.23279772e+38  -1.27016395e+38
  -1.30753017e+38]
f(x)->-4.72477051405387e+78
gradient->[  9.64547885e+39   1.32326980e+40   1.98067904e+40   2.04071363e+40
   2.10074821e+40]
recomputed x->[  9.04513301e+38   1.24090794e+39   1.85739927e+39   1.91369723e+39
   1.96999520e+39]
x->[  9.04513301e+38   1.24090794e+39   1.85739927e+39   1.91369723e+39
   1.96999520e+39]
f(x)->-1.0725254695284578e+81
gradient->[ -1.45323966e+41  -1.99370936e+41  -2.98419744e+41  -3.07464877e+41
  -3.16510010e+41]
recomputed x->[ -1.36278833e+40  -1.86961857e+40  -2.79845752e+40  -2.88327905e+40
  -2.96810058e+40]
x->[ -1.36278833e+40  -1.86961857e+40  -2.79845752e+40  -2.88327905e+40
  -2.96810058e+40]
f(x)->-2.4346386334862815e+83
gradient-

In [24]:
#10,11,12,13
import numpy as np
import sys

a=np.matrix([[11, 4, 7, 10, 13], [4, 17, 10, 13, 16], [7, 10, 23, 16, 19], [10, 13, 16, 29, 22], [13, 16, 19, 22, 25]])
ainv=np.linalg.inv(a)
print(ainv)
anorm=np.linalg.norm(a)
print(anorm)
ainvnorm=np.linalg.norm(ainv)
print(ainvnorm)
cond=np.linalg.cond(a)
print(cond)

#condition number a measure of how close a matrix is to being singular: a matrix with large condition number is nearly singular, whereas a matrix with condition number close to 1 is far from being singular

def singularityTest(x):
    if np.linalg.cond(x) < 1/sys.float_info.epsilon:
        i = np.linalg.inv(x)
        print(i)
        gradientAscent2D
    else:
        print("pretty singular!")
    

singularityTest(np.matrix([[1,1],[1,1]]))

singularityTest(np.matrix([[1,1],[1,1]])+0.1*np.eye(2,dtype=int))

singularityTest(np.matrix([[1,1],[1,1]])+100*np.eye(2,dtype=int))

singularityTest(np.matrix([[1,1],[1,1]])+1*np.eye(2,dtype=int))



[[-0.62  -0.54  -0.36  -0.18   1.1  ]
 [-0.54  -0.305 -0.27  -0.135  0.8  ]
 [-0.36  -0.27  -0.08  -0.09   0.5  ]
 [-0.18  -0.135 -0.09   0.055  0.2  ]
 [ 1.1    0.8    0.5    0.2   -1.6  ]]
79.5298686029
2.90387671915
225.719873163
pretty singular!
[[ 5.23809524 -4.76190476]
 [-4.76190476  5.23809524]]
[[  9.90196078e-03  -9.80392157e-05]
 [ -9.80392157e-05   9.90196078e-03]]
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


C:\Users\Aditya Chatterjee\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\linalg\linalg.py:1487: RuntimeWarning: divide by zero encountered in true_divide
  return s[..., 0]/s[..., -1]


In [25]:
import numpy as np
import scipy.stats as st
#PART 2
#1,2,3,4

def normalProperties(n):
    mu = 0
    sigma = 1
    means = []
    for repetition in range(1000):
        ndist = np.random.normal(mu, sigma, n)
        means.append(np.mean(ndist))
    print("sample size-->"+str(n))
    print("mean-->"+str(np.mean(means)))
    print("standard deviation-->"+str(np.std(means)))
    #using interval function from scipy.stats instead of quantiles
    print("95% confidence interval-->"+str(st.t.interval(0.95, len(means)-1, loc=np.mean(means), scale=st.sem(means))))
    print("-----------------------------------")

for i in [10, 1000, 100000]:
    normalProperties(i)
    
#as the values below indicate, the mean, and standard deviations decrease and the 95% CI tightens as our sample size increases
#that is, our samples' properties become closer to an actual normal distribution with an increase in sample size
    

sample size-->10
mean-->-0.000801686338234
standard deviation-->0.324243010796
95% confidence interval-->(-0.020932552395324436, 0.019329179718855571)
-----------------------------------
sample size-->1000
mean-->0.000204461599245
standard deviation-->0.0317708123688
95% confidence interval-->(-0.0017680526787080234, 0.0021769758771987241)
-----------------------------------
sample size-->100000
mean-->-0.000274490580882
standard deviation-->0.00302806389998
95% confidence interval-->(-0.00046249015759786561, -8.6491004166048863e-05)
-----------------------------------


In [26]:
#5
a, m = 3., 2.  # shape and mode
s = (np.random.pareto(a, 1000) + 1) * m

import matplotlib.pyplot as plt
count, bins, _ = plt.hist(s, 100, normed=True)
fit = a*m**a / bins**(a+1)
plt.plot(bins, max(count)*fit/max(fit), linewidth=2, color='r')
plt.show()

In [27]:
#6,7,8,9,10

def paretoProperties(n):
    mu = 0
    sigma = 1
    means = []
    for repetition in range(1000):
        a, m = 1, 0.5  # shape and mode
        pdist = (np.random.pareto(a, n) + 1) * m
        means.append(np.mean(pdist))
    print("sample size-->"+str(n))
    print("mean-->"+str(np.mean(means)))
    print("standard deviation-->"+str(np.std(means)))
    #using interval function from scipy.stats instead of quantiles
    print("95% confidence interval-->"+str(st.t.interval(0.95, len(means)-1, loc=np.mean(means), scale=st.sem(means))))
    print("-----------------------------------")

for i in [10, 1000, 100000]:
    paretoProperties(i)

sample size-->10
mean-->14.5466031681
standard deviation-->232.183294082
95% confidence interval-->(0.13133240447673167, 28.961873931803495)
-----------------------------------
sample size-->1000
mean-->8.08280216125
standard deviation-->30.7250512073
95% confidence interval-->(6.1752147349772484, 9.9903895875194859)
-----------------------------------
sample size-->100000
mean-->8.82929818624
standard deviation-->16.5624950071
95% confidence interval-->(7.8010034891835884, 9.8575928833022779)
-----------------------------------


In [28]:
#larger variation in properties for pareto distribution due to high-value outliers