In [2]:
import numpy as np

In [3]:
a = np.random.normal(size=(2,2))
print(a)
## matrix rank
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a))
np.linalg.det(a)

[[-1.45012104  0.10862172]
 [ 0.12682459  1.04265778]]
2
-1.52575588859


-1.5257558885947367

## Inverse matrix

In [4]:
a1 = np.linalg.inv(a)
print(a1)
print("\n", a1 @ a)
print("\n", a @ a1)
print("\n", a @ a1 - np.eye(2))

[[-0.6833713   0.07119207]
 [ 0.08312246  0.95042795]]

 [[  1.00000000e+00  -1.38777878e-17]
 [  0.00000000e+00   1.00000000e+00]]

 [[ 1.  0.]
 [ 0.  1.]]

 [[ 0.  0.]
 [ 0.  0.]]


## (Near) singular matrices

In [5]:
## singular matrix
a = np.matrix(np.arange(1,10).reshape(3,3))
print(a)
print("rank=", np.linalg.matrix_rank(a))
np.linalg.inv(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
rank= 2


matrix([[ -4.50359963e+15,   9.00719925e+15,  -4.50359963e+15],
        [  9.00719925e+15,  -1.80143985e+16,   9.00719925e+15],
        [ -4.50359963e+15,   9.00719925e+15,  -4.50359963e+15]])

In [12]:
n=0.1
for i in range(5):
    b = a + n*np.eye(3)
    print(b)
    print("rank=", np.linalg.matrix_rank(b))
    b1 = np.linalg.inv(b)
    print("\n", b1@b)
    print('\n', b1@b - np.eye(3))
    n/=10
    

[[ 1.1  3.   5. ]
 [ 3.   5.1  7. ]
 [ 5.   7.   9.1]]
rank= 3

 [[  1.00000000e+00  -7.10542736e-15  -7.10542736e-15]
 [  0.00000000e+00   1.00000000e+00   1.06581410e-14]
 [  1.77635684e-15  -3.55271368e-15   1.00000000e+00]]

 [[ -1.77635684e-15  -7.10542736e-15  -7.10542736e-15]
 [  0.00000000e+00   3.55271368e-15   1.06581410e-14]
 [  1.77635684e-15  -3.55271368e-15  -1.77635684e-15]]
[[ 1.01  3.    5.  ]
 [ 3.    5.01  7.  ]
 [ 5.    7.    9.01]]
rank= 3

 [[  1.00000000e+00   4.26325641e-14   8.52651283e-14]
 [ -2.84217094e-14   1.00000000e+00   0.00000000e+00]
 [  2.84217094e-14  -2.84217094e-14   1.00000000e+00]]

 [[  5.68434189e-14   4.26325641e-14   8.52651283e-14]
 [ -2.84217094e-14  -2.84217094e-14   0.00000000e+00]
 [  2.84217094e-14  -2.84217094e-14   0.00000000e+00]]
[[ 1.001  3.     5.   ]
 [ 3.     5.001  7.   ]
 [ 5.     7.     9.001]]
rank= 3

 [[  1.00000000e+00   4.54747351e-13   9.09494702e-13]
 [ -4.54747351e-13   1.00000000e+00  -9.09494702e-13]
 [  3.41060513

## Eigenvalues

In [7]:
a = np.matrix(np.arange(1,10).reshape(3,3))
print(a)
ev = np.linalg.eig(a)
print('\neigenvalues\n', ev)
val, vec = np.linalg.eig(a)
print('\neigenvalues\n', val)
print('\ncondition number', np.linalg.cond(a))
print('\neigenvectors\n', vec)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

eigenvalues
 (array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]), matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

eigenvalues
 [  1.61168440e+01  -1.11684397e+00  -1.30367773e-15]

condition number 3.81314706063e+16

eigenvectors
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## diagonalization

In [8]:
a = np.matrix(np.arange(1,10).reshape(3,3))
a = 0.5*(a + a.T)
print(a)
val, vec = np.linalg.eig(a)
print('\neigenvalues\n', val)
print('\neigenvectors\n', vec)
L = np.diag(val)
C = vec
print('C\n', C)
C1 = np.linalg.inv(C)
print('\nC inverse\n', C1)
print('\ndiagonal form\n', C @ L @ C1)

[[ 1.  3.  5.]
 [ 3.  5.  7.]
 [ 5.  7.  9.]]

eigenvalues
 [  1.64582364e+01  -1.45823643e+00   1.62591776e-16]

eigenvectors
 [[-0.35162514 -0.84243284  0.40824829]
 [-0.55335618 -0.1647127  -0.81649658]
 [-0.75508721  0.51300744  0.40824829]]
C
 [[-0.35162514 -0.84243284  0.40824829]
 [-0.55335618 -0.1647127  -0.81649658]
 [-0.75508721  0.51300744  0.40824829]]

C inverse
 [[-0.35162514 -0.55335618 -0.75508721]
 [-0.84243284 -0.1647127   0.51300744]
 [ 0.40824829 -0.81649658  0.40824829]]

diagonal form
 [[ 1.  3.  5.]
 [ 3.  5.  7.]
 [ 5.  7.  9.]]
